<?php
//copied from cw/fencers_weapon_control.php
$array_issues = array(
    "FIE mark on blade",
    "Arm gap and weight",
    "Arm lenght",
    "Blade lenght",
    "Grip lenght",
    "Form and depth of the guard",
    "Guard oxydation / deformation",
    "Excentricity of the blade",
    "Blade flexibility",
    "Curve on the blade",
    "Foucault current device",
    "Point and arm size",
    "Spring of the point",
    "Total travel of the point",
    "Residual travel of the point",
    "Isolation of the point",
    "Resistance of the arm",
    "Length / condition of bodywire / maskwire",
    "Resistance of bodywire / maskwire",
    "Mask: FIE mark",
    "Mask: condition and insulation",
    "Mask: resistance (sabre, foil)",
    "Metallic jacket condition",
    "Metallic jacket resistance",
    "Sabre glove / overlay condition",
    "Sabre glove / overlay resistance",
    "Glove condition",
    "Jacket condition",
    "Reeches condition",
    "Under-plastron condition",
    "Foil chest protector",
    "Socks",
    "Incorrect name printing",
    "Incorrect nation logo",
    "Commercial",
    "Other items",
);
?>